import os
from dotenv import load_dotenv

load_dotenv(".env")

GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
GOOGLE_APPLICATION_CREDENTIALS_STRING = os.getenv(
    "GOOGLE_APPLICATION_CREDENTIALS_STRING"
)
GOOGLE_CREDENTIALS = os.getenv("GOOGLE_CREDENTIALS")
